#!/bin/sh

start() {
	[ ! -f "/etc/options_menu/optiond" ] && standby_watchdog &
}

stop() {
	killall standby_watchdog
}

case "$1" in
start)
	start
;;
stop)
	stop
;;
restart)
	stop
	start
;;
*)
	echo "standby_watchdog: Please use start, stop, or restart."
	exit 1
;;
esac
